/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinyButton: typeof import('@opentiny/vue-button')['default']
    TinyButtonGroup: typeof import('@opentiny/vue-button-group')['default']
    TinyForm: typeof import('@opentiny/vue-form')['default']
    TinyFormItem: typeof import('@opentiny/vue-form-item')['default']
    TinyGrid: typeof import('@opentiny/vue-grid')['default']
    TinyGridColumn: typeof import('@opentiny/vue-grid-column')['default']
    TinyImage: typeof import('@opentiny/vue-image')['default']
    TinyImageUpload: typeof import('@opentiny/vue-image-upload')['default']
    TinyInput: typeof import('@opentiny/vue-input')['default']
    TinyInputNumber: typeof import('@opentiny/vue-input-number')['default']
    TinyModal: typeof import('@opentiny/vue-modal')['default']
    TinyNumeric: typeof import('@opentiny/vue-numeric')['default']
    TinyOption: typeof import('@opentiny/vue-option')['default']
    TinyRobotChat: typeof import('./src/components/tiny-robot-chat.vue')['default']
    TinySelect: typeof import('@opentiny/vue-select')['default']
    TinyTag: typeof import('@opentiny/vue-tag')['default']
  }
}
