/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AntDesignX: typeof import('./src/components/ant-design-x.vue')['default']
    ReactiveMarkdown: typeof import('./src/components/ReactiveMarkdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinyBaseSelect: typeof import('@opentiny/vue-base-select')['default']
    TinyButton: typeof import('@opentiny/vue-button')['default']
    TinyDialogBox: typeof import('@opentiny/vue-dialog-box')['default']
    TinyForm: typeof import('@opentiny/vue-form')['default']
    TinyFormItem: typeof import('@opentiny/vue-form-item')['default']
    TinyGrid: typeof import('@opentiny/vue-grid')['default']
    TinyGridColumn: typeof import('@opentiny/vue-grid-column')['default']
    TinyImage: typeof import('@opentiny/vue-image')['default']
    TinyInput: typeof import('@opentiny/vue-input')['default']
    TinyOption: typeof import('@opentiny/vue-option')['default']
    TinyQrCode: typeof import('@opentiny/vue-qr-code')['default']
    TinyRobotChat: typeof import('./src/components/tiny-robot-chat.vue')['default']
    TinyTag: typeof import('@opentiny/vue-tag')['default']
    TinyTree: typeof import('@opentiny/vue-tree')['default']
  }
}
